### MakeKmers.smk: Finding male-specific kmers in a Goby genome assembly
# ===========================================================================
# S. Lorena Ament-Velasquez
# 2025-03-19
# +++++++++++++++++++++++++++++++++++++++++++++++++

# Sample IDs
SampleIDs: ["PflaHELAf", "PflaKGBDf", "PflaHELEm", "PflaKGBHm"]
# Path to BAM files of Illumina samples mapped to the reference
path2bams: "../05_GobyMapping/mapping"
# The reference genome (absolute path)
REFGenome: "../../Zenodo/Assembly/fGobFla1.fasta" # Available in Zenodo repository
# satDNA annotation
satDNA: "../../Zenodo/Annotation/fGobFla1-GobyTideCluster_v1.00.gff3" # Available in Zenodo repository
# Scripts
GobyIlluCovDist: "scripts/GobyIlluCovDist.R"

